### PR TITLE
Fixed Issue #17, user was able to delete message of other users. 

### LINKED ISSUE #17: By Pull Request On Issue 14, a bug generated.
issue #14 

**Describe the bug**
What happened is, anyone can delete anyone's message, and this shouldn't happend.

**Additional context**
What you can do to solve it, check if the user on the message is equal to the user gonna delete the message, if both are same then it should be deleted otherwise delete option should not be there.

### PR DESCRIPTION
**Pull request by sanskarbansal**
Fixes #17 

#### Short description of what this resolves:
Earlier user was able to delete other users message, this PR fixes this issue by checking in backend if the user who is deleting the post is the one who is logged in or not. 

#### Changes proposed in this pull request:
- In index.js (client) verify that the whether to show delete message button or not. 
- In backend verify if the user who is deleting the post is the one who is logged in . 

#### Checklist

- [x] My branch is up-to-date with the Upstream `development` branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by sanskarbansal** [comment]
@Creatoon please review my PR.

File: controllers/messageController.js [hunk 1]
```diff
@@ -3,4 +3,18 @@ const factory = require('./../controllers/handlerFactory');
...
+      status: 'fail',
+      data: 'You are not permitted to perform this task.'
+    });
+  }
+  chat.remove();
+  res.status(204).json({
+    status: 'success',
+    data: null
+  });
+  //   factory.deleteOne(Chat);
```
Comment (Creatoon) [inline controllers/messageController.js]:
```suggestion
 
```

**Review by Creatoon — CHANGES_REQUESTED** [review]

**Comment by Creatoon** [comment]
@sanskarbansal Good Job 👍🏽
